// -- This file has been autogenerated - do not modify by hand
// -- This file is automatically included when necessary, don't include it in your own program
#ifndef _DEV_ATmega1284P_H_
#define _DEV_ATmega1284P_H_

#include "../libdefs.h"

#define EEPROM_SIZE 4096
// -- include EEPROM support --
#include <avr/eeprom.h>
// -------------- Define the I/O ports that haven't been disabled by the system file ------------
#ifdef PORTA
// Define Port A
	IOPort PROGMEM _PORTA={_SFR_MEM_ADDR(PORTA),_SFR_MEM_ADDR(DDRA),_SFR_MEM_ADDR(PINA)};
# ifdef PA0
	IOPin PROGMEM _A0 = { &_PORTA, BV(PA0)};
#	define A0 &_A0
#	undef PA0
# endif
# ifdef PA1
	IOPin PROGMEM _A1 = { &_PORTA, BV(PA1)};
#	define A1 &_A1
#	undef PA1
# endif
# ifdef PA2
	IOPin PROGMEM _A2 = { &_PORTA, BV(PA2)};
#	define A2 &_A2
#	undef PA2
# endif
# ifdef PA3
	IOPin PROGMEM _A3 = { &_PORTA, BV(PA3)};
#	define A3 &_A3
#	undef PA3
# endif
# ifdef PA4
	IOPin PROGMEM _A4 = { &_PORTA, BV(PA4)};
#	define A4 &_A4
#	undef PA4
# endif
# ifdef PA5
	IOPin PROGMEM _A5 = { &_PORTA, BV(PA5)};
#	define A5 &_A5
#	undef PA5
# endif
# ifdef PA6
	IOPin PROGMEM _A6 = { &_PORTA, BV(PA6)};
#	define A6 &_A6
#	undef PA6
# endif
# ifdef PA7
	IOPin PROGMEM _A7 = { &_PORTA, BV(PA7)};
#	define A7 &_A7
#	undef PA7
# endif
//undefine pins to stop them being used directly
# undef PORTA
# undef DDRA
# undef PINA
#endif

#ifdef PORTB
// Define Port B
	IOPort PROGMEM _PORTB={_SFR_MEM_ADDR(PORTB),_SFR_MEM_ADDR(DDRB),_SFR_MEM_ADDR(PINB)};
# ifdef PB0
	IOPin PROGMEM _B0 = { &_PORTB, BV(PB0)};
#	define B0 &_B0
#	undef PB0
# endif
# ifdef PB1
	IOPin PROGMEM _B1 = { &_PORTB, BV(PB1)};
#	define B1 &_B1
#	undef PB1
# endif
# ifdef PB2
	IOPin PROGMEM _B2 = { &_PORTB, BV(PB2)};
#	define B2 &_B2
#	undef PB2
# endif
# ifdef PB3
	IOPin PROGMEM _B3 = { &_PORTB, BV(PB3)};
#	define B3 &_B3
#	undef PB3
# endif
# ifdef PB4
	IOPin PROGMEM _B4 = { &_PORTB, BV(PB4)};
#	define B4 &_B4
#	undef PB4
# endif
# ifdef PB5
	IOPin PROGMEM _B5 = { &_PORTB, BV(PB5)};
#	define B5 &_B5
#	undef PB5
# endif
# ifdef PB6
	IOPin PROGMEM _B6 = { &_PORTB, BV(PB6)};
#	define B6 &_B6
#	undef PB6
# endif
# ifdef PB7
	IOPin PROGMEM _B7 = { &_PORTB, BV(PB7)};
#	define B7 &_B7
#	undef PB7
# endif
//undefine pins to stop them being used directly
# undef PORTB
# undef DDRB
# undef PINB
#endif

#ifdef PORTC
// Define Port C
	IOPort PROGMEM _PORTC={_SFR_MEM_ADDR(PORTC),_SFR_MEM_ADDR(DDRC),_SFR_MEM_ADDR(PINC)};
# ifdef PC0
	IOPin PROGMEM _C0 = { &_PORTC, BV(PC0)};
#	define C0 &_C0
#	undef PC0
# endif
# ifdef PC1
	IOPin PROGMEM _C1 = { &_PORTC, BV(PC1)};
#	define C1 &_C1
#	undef PC1
# endif
# ifdef PC2
	IOPin PROGMEM _C2 = { &_PORTC, BV(PC2)};
#	define C2 &_C2
#	undef PC2
# endif
# ifdef PC3
	IOPin PROGMEM _C3 = { &_PORTC, BV(PC3)};
#	define C3 &_C3
#	undef PC3
# endif
# ifdef PC4
	IOPin PROGMEM _C4 = { &_PORTC, BV(PC4)};
#	define C4 &_C4
#	undef PC4
# endif
# ifdef PC5
	IOPin PROGMEM _C5 = { &_PORTC, BV(PC5)};
#	define C5 &_C5
#	undef PC5
# endif
# ifdef PC6
	IOPin PROGMEM _C6 = { &_PORTC, BV(PC6)};
#	define C6 &_C6
#	undef PC6
# endif
# ifdef PC7
	IOPin PROGMEM _C7 = { &_PORTC, BV(PC7)};
#	define C7 &_C7
#	undef PC7
# endif
//undefine pins to stop them being used directly
# undef PORTC
# undef DDRC
# undef PINC
#endif

#ifdef PORTD
// Define Port D
	IOPort PROGMEM _PORTD={_SFR_MEM_ADDR(PORTD),_SFR_MEM_ADDR(DDRD),_SFR_MEM_ADDR(PIND)};
# ifdef PD0
	IOPin PROGMEM _D0 = { &_PORTD, BV(PD0)};
#	define D0 &_D0
#	undef PD0
# endif
# ifdef PD1
	IOPin PROGMEM _D1 = { &_PORTD, BV(PD1)};
#	define D1 &_D1
#	undef PD1
# endif
# ifdef PD2
	IOPin PROGMEM _D2 = { &_PORTD, BV(PD2)};
#	define D2 &_D2
#	undef PD2
# endif
# ifdef PD3
	IOPin PROGMEM _D3 = { &_PORTD, BV(PD3)};
#	define D3 &_D3
#	undef PD3
# endif
# ifdef PD4
	IOPin PROGMEM _D4 = { &_PORTD, BV(PD4)};
#	define D4 &_D4
#	undef PD4
# endif
# ifdef PD5
	IOPin PROGMEM _D5 = { &_PORTD, BV(PD5)};
#	define D5 &_D5
#	undef PD5
# endif
# ifdef PD6
	IOPin PROGMEM _D6 = { &_PORTD, BV(PD6)};
#	define D6 &_D6
#	undef PD6
# endif
# ifdef PD7
	IOPin PROGMEM _D7 = { &_PORTD, BV(PD7)};
#	define D7 &_D7
#	undef PD7
# endif
//undefine pins to stop them being used directly
# undef PORTD
# undef DDRD
# undef PIND
#endif

// -------------- End of I/O ports --------------------------------------------------------------

// -------------- Define the PWM pins that haven't been disabled by the system file -------------
#ifdef B3
# define PWM0A B3
#else
# define PWM0A null
#endif
#ifdef B4
# define PWM0B B4
#else
# define PWM0B null
#endif
#ifdef D5
# define PWM1A D5
#else
# define PWM1A null
#endif
#ifdef D4
# define PWM1B D4
#else
# define PWM1B null
#endif
#ifdef D7
# define PWM2A D7
#else
# define PWM2A null
#endif
#ifdef D6
# define PWM2B D6
#else
# define PWM2B null
#endif
#ifdef B6
# define PWM3A B6
#else
# define PWM3A null
#endif
#ifdef B7
# define PWM3B B7
#else
# define PWM3B null
#endif
// -------------- End of PWM pins ---------------------------------------------------------------

// -------------- Define the timers -------------------------------------------------------------

// Create Timer 0
TimerData __timer0_data = MAKE_TIMER_DATA(0);
TimerDataCompare __timer0CompareA_data = MAKE_TIMER_COMPARE_DATA();
TimerDataCompare __timer0CompareB_data = MAKE_TIMER_COMPARE_DATA();
TimerCompare PROGMEM __timer0Compare[] = {
	MAKE_TIMER_COMPARE(__timer0CompareA_data,0,TIMSK0,OCIE0A,OCR0A,TIFR0,OCF0A,TCCR0A,COM0A0,PWM0A),
	MAKE_TIMER_COMPARE(__timer0CompareB_data,0,TIMSK0,OCIE0B,OCR0B,TIFR0,OCF0B,TCCR0A,COM0B0,PWM0B)
};
#define TIMER0_COMPAREA &__timer0Compare[0]
#define TIMER0_COMPAREB &__timer0Compare[1]

// Create Timer 1
TimerData __timer1_data = MAKE_TIMER_DATA(0);
TimerDataCompare __timer1CompareA_data = MAKE_TIMER_COMPARE_DATA();
TimerDataCompare __timer1CompareB_data = MAKE_TIMER_COMPARE_DATA();
TimerCompare PROGMEM __timer1Compare[] = {
	MAKE_TIMER_COMPARE(__timer1CompareA_data,1,TIMSK1,OCIE1A,OCR1A,TIFR1,OCF1A,TCCR1A,COM1A0,PWM1A),
	MAKE_TIMER_COMPARE(__timer1CompareB_data,1,TIMSK1,OCIE1B,OCR1B,TIFR1,OCF1B,TCCR1A,COM1B0,PWM1B)
};
#define TIMER1_COMPAREA &__timer1Compare[0]
#define TIMER1_COMPAREB &__timer1Compare[1]

// Create Timer 2
TimerData __timer2_data = MAKE_TIMER_DATA(0);
TimerDataCompare __timer2CompareA_data = MAKE_TIMER_COMPARE_DATA();
TimerDataCompare __timer2CompareB_data = MAKE_TIMER_COMPARE_DATA();
TimerCompare PROGMEM __timer2Compare[] = {
	MAKE_TIMER_COMPARE(__timer2CompareA_data,2,TIMSK2,OCIE2A,OCR2A,TIFR2,OCF2A,TCCR2A,COM2A0,PWM2A),
	MAKE_TIMER_COMPARE(__timer2CompareB_data,2,TIMSK2,OCIE2B,OCR2B,TIFR2,OCF2B,TCCR2A,COM2B0,PWM2B)
};
#define TIMER2_COMPAREA &__timer2Compare[0]
#define TIMER2_COMPAREB &__timer2Compare[1]

// Create Timer 3
TimerData __timer3_data = MAKE_TIMER_DATA(0);
TimerDataCompare __timer3CompareA_data = MAKE_TIMER_COMPARE_DATA();
TimerDataCompare __timer3CompareB_data = MAKE_TIMER_COMPARE_DATA();
TimerCompare PROGMEM __timer3Compare[] = {
	MAKE_TIMER_COMPARE(__timer3CompareA_data,3,TIMSK3,OCIE3A,OCR3A,TIFR3,OCF3A,TCCR3A,COM3A0,PWM3A),
	MAKE_TIMER_COMPARE(__timer3CompareB_data,3,TIMSK3,OCIE3B,OCR3B,TIFR3,OCF3B,TCCR3A,COM3B0,PWM3B)
};
#define TIMER3_COMPAREA &__timer3Compare[0]
#define TIMER3_COMPAREB &__timer3Compare[1]

// Input Capture pins for each timer
#define InputCapture0 null
#ifdef D6
#define InputCapture1 D6
#else
#define InputCapture1 null
#endif
#define InputCapture2 null
#ifdef D6
#define InputCapture3 D6
#else
#define InputCapture3 null
#endif

const PROGMEM Timer PROGMEM pgm_Timers[] = {
	MAKE_TIMER(__timer0_data,TCNT0,TCCR0B, FALSE, FALSE, TIMER_3BIT_MODES,TCCR0A,WGM00,TCCR0A,WGM01,TCCR0B,WGM02,UNUSED_PORT,0,__timer0Compare, TIMSK0,TOIE0, TIFR0,TOV0, UNUSED_PORT, UNUSED_PORT,0, UNUSED_PORT,0, UNUSED_PORT,0, InputCapture0),
	MAKE_TIMER(__timer1_data,TCNT1,TCCR1B, TRUE, FALSE, TIMER_ALL_MODES,TCCR1A,WGM10,TCCR1A,WGM11,TCCR1B,WGM12,TCCR1B,WGM13,__timer1Compare, TIMSK1,TOIE1, TIFR1,TOV1, ICR1, TIMSK1,ICIE1, TIFR1,ICF1, TCCR1B,ICES1, InputCapture1),
	MAKE_TIMER(__timer2_data,TCNT2,TCCR2B, FALSE, TRUE, TIMER_3BIT_MODES,TCCR2A,WGM20,TCCR2A,WGM21,TCCR2B,WGM22,UNUSED_PORT,0,__timer2Compare, TIMSK2,TOIE2, TIFR2,TOV2, UNUSED_PORT, UNUSED_PORT,0, UNUSED_PORT,0, UNUSED_PORT,0, InputCapture2),
	MAKE_TIMER(__timer3_data,TCNT3,TCCR3B, TRUE, FALSE, TIMER_ALL_MODES,TCCR3A,WGM30,TCCR3A,WGM31,TCCR3B,WGM32,TCCR3B,WGM33,__timer3Compare, TIMSK3,TOIE3, TIFR3,TOV3, ICR3, TIMSK3,ICIE3, TIFR3,ICF3, TCCR3B,ICES3, InputCapture3)
};
const uint8_t NUMBER_OF_TIMERS =  (sizeof(pgm_Timers)/sizeof(Timer));
#define TIMER0 &pgm_Timers[0]
#define TIMER1 &pgm_Timers[1]
#define TIMER2 &pgm_Timers[2]
#define TIMER3 &pgm_Timers[3]
// -------------- End of timer definitions ------------------------------------------------------

// -------------- Define the UARTs --------------------------------------------------------------
#include "../uart.h"
// -- Create receive buffers
#ifdef UART_RX_BUFFER_SIZE
# ifndef UART0_RX_BUFFER_SIZE
   // Use default value
#  define UART0_RX_BUFFER_SIZE  UART_RX_BUFFER_SIZE
# endif
# ifndef UART1_RX_BUFFER_SIZE
   // Use default value
#  define UART1_RX_BUFFER_SIZE  UART_RX_BUFFER_SIZE
# endif
#endif


#ifdef UART0_RX_BUFFER_SIZE
  unsigned char rx0Buf[UART0_RX_BUFFER_SIZE];
  cBuffer rx0Buffer = MAKE_BUFFER(rx0Buf);
# define rx0B &rx0Buffer
#else
# define rx0B null
#endif

#ifdef UART1_RX_BUFFER_SIZE
  unsigned char rx1Buf[UART1_RX_BUFFER_SIZE];
  cBuffer rx1Buffer = MAKE_BUFFER(rx1Buf);
# define rx1B &rx1Buffer
#else
# define rx1B null
#endif

// -- Create transmit buffers
#ifdef UART_TX_BUFFER_SIZE
# ifndef UART0_TX_BUFFER_SIZE
   // Use default value
#  define UART0_TX_BUFFER_SIZE  UART_TX_BUFFER_SIZE
# endif
# ifndef UART1_TX_BUFFER_SIZE
   // Use default value
#  define UART1_TX_BUFFER_SIZE  UART_TX_BUFFER_SIZE
# endif
#endif


#ifdef UART0_TX_BUFFER_SIZE
  unsigned char tx0Buf[UART0_TX_BUFFER_SIZE];
  cBuffer tx0Buffer = MAKE_BUFFER(tx0Buf);
# define tx0B &tx0Buffer
#else
# define tx0B null
#endif

#ifdef UART1_TX_BUFFER_SIZE
  unsigned char tx1Buf[UART1_TX_BUFFER_SIZE];
  cBuffer tx1Buffer = MAKE_BUFFER(tx1Buf);
# define tx1B &tx1Buffer
#else
# define tx1B null
#endif

// -- Define the pin used for the SPI clock, if supported, for each uart
/* UART0 has SPI mode with clock on B0*/
#ifdef B0
# define UART_SPI_CLOCK0 B0
#else
# define UART_SPI_CLOCK0 null
#endif
/* UART1 has SPI mode with clock on D4*/
#ifdef D4
# define UART_SPI_CLOCK1 D4
#else
# define UART_SPI_CLOCK1 null
#endif


#define _NUM_UARTS 2
const uint8_t NUM_UARTS = _NUM_UARTS;

HW_UART Uarts[] = {
	MAKE_UART_BUFFERED(rx0B,tx0B,UCSR0A,UCSR0B,UBRR0L,UBRR0H,UDR0,UART_SPI_CLOCK0,2,D0,D1,&uart0GetByte,&uart0SendByte),
	MAKE_UART_BUFFERED(rx1B,tx1B,UCSR1A,UCSR1B,UBRR1L,UBRR1H,UDR1,UART_SPI_CLOCK1,2,D2,D3,&uart1GetByte,&uart1SendByte)
};

#define UART0 &Uarts[0]
#define UART1 &Uarts[1]
// -------------- End of UART definitions -------------------------------------------------------

// -------------- Start of ADC channel definitions ----------------------------------------------
#define ADC0 ADC_NUMBER_TO_CHANNEL(0)
#define ADC1 ADC_NUMBER_TO_CHANNEL(1)
#define ADC2 ADC_NUMBER_TO_CHANNEL(2)
#define ADC3 ADC_NUMBER_TO_CHANNEL(3)
#define ADC4 ADC_NUMBER_TO_CHANNEL(4)
#define ADC5 ADC_NUMBER_TO_CHANNEL(5)
#define ADC6 ADC_NUMBER_TO_CHANNEL(6)
#define ADC7 ADC_NUMBER_TO_CHANNEL(7)
const uint8_t NUM_ADC_CHANNELS = 8;
// -------------- End of ADC channel definitions ------------------------------------------------

// -------------- Define which IOPin is used by the pin change interrupts --------------------------------
const IOPin* PROGMEM PCINT_PINS[]={
// PCINT 0
#	ifdef A0
	A0,
#	else
	null,
#	endif
// PCINT 1
#	ifdef A1
	A1,
#	else
	null,
#	endif
// PCINT 2
#	ifdef A2
	A2,
#	else
	null,
#	endif
// PCINT 3
#	ifdef A3
	A3,
#	else
	null,
#	endif
// PCINT 4
#	ifdef A4
	A4,
#	else
	null,
#	endif
// PCINT 5
#	ifdef A5
	A5,
#	else
	null,
#	endif
// PCINT 6
#	ifdef A6
	A6,
#	else
	null,
#	endif
// PCINT 7
#	ifdef A7
	A7,
#	else
	null,
#	endif
// PCINT 8
#	ifdef B0
	B0,
#	else
	null,
#	endif
// PCINT 9
#	ifdef B1
	B1,
#	else
	null,
#	endif
// PCINT 10
#	ifdef B2
	B2,
#	else
	null,
#	endif
// PCINT 11
#	ifdef B3
	B3,
#	else
	null,
#	endif
// PCINT 12
#	ifdef B4
	B4,
#	else
	null,
#	endif
// PCINT 13
#	ifdef B5
	B5,
#	else
	null,
#	endif
// PCINT 14
#	ifdef B6
	B6,
#	else
	null,
#	endif
// PCINT 15
#	ifdef B7
	B7,
#	else
	null,
#	endif
// PCINT 16
#	ifdef C0
	C0,
#	else
	null,
#	endif
// PCINT 17
#	ifdef C1
	C1,
#	else
	null,
#	endif
// PCINT 18
#	ifdef C2
	C2,
#	else
	null,
#	endif
// PCINT 19
#	ifdef C3
	C3,
#	else
	null,
#	endif
// PCINT 20
#	ifdef C4
	C4,
#	else
	null,
#	endif
// PCINT 21
#	ifdef C5
	C5,
#	else
	null,
#	endif
// PCINT 22
#	ifdef C6
	C6,
#	else
	null,
#	endif
// PCINT 23
#	ifdef C7
	C7,
#	else
	null,
#	endif
// PCINT 24
#	ifdef D0
	D0,
#	else
	null,
#	endif
// PCINT 25
#	ifdef D1
	D1,
#	else
	null,
#	endif
// PCINT 26
#	ifdef D2
	D2,
#	else
	null,
#	endif
// PCINT 27
#	ifdef D3
	D3,
#	else
	null,
#	endif
// PCINT 28
#	ifdef D4
	D4,
#	else
	null,
#	endif
// PCINT 29
#	ifdef D5
	D5,
#	else
	null,
#	endif
// PCINT 30
#	ifdef D6
	D6,
#	else
	null,
#	endif
// PCINT 31
#	ifdef D7
	D7
#	else
	null
#	endif
};
#define _NUM_PCINT_PINS 32
const uint8_t NUM_PCINT_PINS = 32;
// -------------- End of pin change definitions - ------------------------------------------------

#endif
